### ISSUE TITLE
Better mention of build logs [request]

### ISSUE THREAD

**Issue by CoderJoshDK** [railwayapp/docs#526]
Right now, the docs don't have great exposure to build logs and how to read / debug them.

All the docs for logs, point to deployment logs. The most typical thing you want to check. But I think there should be more on build logs. The only mention I could find, was https://docs.railway.app/guides/logs#builddeploy-panel.

Somewhere in the https://docs.railway.app/guides/build-configuration (or even a new tab for build logs inside https://docs.railway.app/guides/builds) should have details about where to find the logs and common errors / gotchas. 

Please add onto this issue if you can think of any other topics that should be mentioned for this doc additions. But the common issues I see / want talked about:

* breakdown each section of the log (region vs nixpacks steps vs pushing vs etc)
* Common issues with long pushes (reasons / how to create smaller build files; like using docker to have staged building)

I am sure there are more important topics in this regard. But these are the main things I can think about / want to see.

Why make this change?
For one, it will help when trying to help someone. Frequently, we ask for logs, and they are very confused or don't send the correct portion of log. Having a page / section to point to, when asking for logs, might help clear things up.

**Comment by brody192** [comment]
Hello, thank you for opening this issue!

My thoughts on the points you have brought up -

> Right now, the docs don't have great exposure to build logs ... 

#### And

> All the docs for logs, point to deployment logs. The most typical thing you want to check. But I think there should be more on build logs.

True, all of the screenshots I can see show only the deploy logs being opened!

> ... and how to read / debug them.

It's my opinion that teaching users how to debug build logs would be a bit out of the scope of our docs as the tactics and knowledge used for debugging and reading through build logs change with every language, program, and error.

> breakdown each section of the log (region vs nixpacks steps vs pushing vs etc)

- Region - That is not something we are going to document since the V2 builder does not print the region, making documentation on this stale once the V2 builder is the default and only option.

- Nixpacks Steps - AKA the Build Table, this should be mentioned as it's currently not mentioned anywhere in the current docs.

- Pushing - This is also not something we are going to document for the same reason as the first point, the V2 builder does not print out a publishing step.

- ETC - Nothing else to the build logs besides the health check but that doesn't need expanding on because the stage prints `Starting Healthcheck` with extra info on the path and time window.

> Common issues with long pushes (reasons / how to create smaller build files; like using docker to have staged building)

- Common issues with long pushes (reasons) - With the work being done on the new builder long publish times will not be an issue, the goal being to pull an image at 1GB/s so documentation here would become stale.

- Common issues with long pushes (how to create smaller build files; like using docker to have staged building) - This also would IMO be out of the scope of our docs for a similar reason as before, it's an incredibly complex subject with no real tie to Railway the platform, with plenty of great resources online for this already. 

> I am sure there are more important topics in this regard. But these are the main things I can think about / want to see.

Throughout writing this, I was unable to come up with anything else to talk about regarding build logs, but I'm open to ideas.

Sat on all of this for a long time, and this PR #530 is what I could come up with.
